name = "tick"
compatibility_date = "2023-01-01"
compatibility_flags = ["nodejs_compat"]
vars = { ENVIRONMENT = "stag" }

d1_databases = [
  { binding = "DB", name = "tick", database_id = "93dca6c0-d6ba-48c1-9aa6-b51d477300bb" }
]

[env.stag]
vars = { ENVIRONMENT = "stag" }
route = { pattern = "stag.tick.lohxt.space", custom_domain = true }
d1_databases = [
  { binding = "DB", name = "tick", database_id = "93dca6c0-d6ba-48c1-9aa6-b51d477300bb" }
]

[env.prod]
vars = { ENVIRONMENT = "prod" }
route = { pattern = "prod.tick.lohxt.space", custom_domain = true }
d1_databases = [
  { binding = "DB", name = "tick", database_id = "93dca6c0-d6ba-48c1-9aa6-b51d477300bb" }
]